// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_cov.h"
#include "verilated_timing.h"

class Vtop__Syms;
class Vtop_sky130_sram_2kbyte_1rw1r_32x512_8;


class Vtop___024root final : public VerilatedModule {
  public:
    // CELLS
    Vtop_sky130_sram_2kbyte_1rw1r_32x512_8* __PVT__soc_sram__DOT__sram__DOT__genblk1__BRA__0__KET____DOT__sram1;
    Vtop_sky130_sram_2kbyte_1rw1r_32x512_8* __PVT__soc_sram__DOT__sram__DOT__genblk1__BRA__1__KET____DOT__sram1;
    Vtop_sky130_sram_2kbyte_1rw1r_32x512_8* __PVT__soc_sram__DOT__sram__DOT__genblk1__BRA__2__KET____DOT__sram1;
    Vtop_sky130_sram_2kbyte_1rw1r_32x512_8* __PVT__soc_sram__DOT__sram__DOT__genblk1__BRA__3__KET____DOT__sram1;
    Vtop_sky130_sram_2kbyte_1rw1r_32x512_8* __PVT__soc_sram__DOT__sram__DOT__genblk1__BRA__4__KET____DOT__sram1;
    Vtop_sky130_sram_2kbyte_1rw1r_32x512_8* __PVT__soc_sram__DOT__sram__DOT__genblk1__BRA__5__KET____DOT__sram1;
    Vtop_sky130_sram_2kbyte_1rw1r_32x512_8* __PVT__soc_sram__DOT__sram__DOT__genblk1__BRA__6__KET____DOT__sram1;
    Vtop_sky130_sram_2kbyte_1rw1r_32x512_8* __PVT__soc_sram__DOT__sram__DOT__genblk1__BRA__7__KET____DOT__sram1;
    Vtop_sky130_sram_2kbyte_1rw1r_32x512_8* __PVT__soc_sram__DOT__sram__DOT__genblk1__BRA__8__KET____DOT__sram1;
    Vtop_sky130_sram_2kbyte_1rw1r_32x512_8* __PVT__soc_sram__DOT__sram__DOT__genblk1__BRA__9__KET____DOT__sram1;
    Vtop_sky130_sram_2kbyte_1rw1r_32x512_8* __PVT__soc_sram__DOT__sram__DOT__genblk1__BRA__10__KET____DOT__sram1;
    Vtop_sky130_sram_2kbyte_1rw1r_32x512_8* __PVT__soc_sram__DOT__sram__DOT__genblk1__BRA__11__KET____DOT__sram1;
    Vtop_sky130_sram_2kbyte_1rw1r_32x512_8* __PVT__soc_sram__DOT__sram__DOT__genblk1__BRA__12__KET____DOT__sram1;
    Vtop_sky130_sram_2kbyte_1rw1r_32x512_8* __PVT__soc_sram__DOT__sram__DOT__genblk1__BRA__13__KET____DOT__sram1;
    Vtop_sky130_sram_2kbyte_1rw1r_32x512_8* __PVT__soc_sram__DOT__sram__DOT__genblk1__BRA__14__KET____DOT__sram1;
    Vtop_sky130_sram_2kbyte_1rw1r_32x512_8* __PVT__soc_sram__DOT__sram__DOT__genblk1__BRA__15__KET____DOT__sram1;
    Vtop_sky130_sram_2kbyte_1rw1r_32x512_8* __PVT__soc_sram__DOT__sram__DOT__genblk1__BRA__16__KET____DOT__sram1;
    Vtop_sky130_sram_2kbyte_1rw1r_32x512_8* __PVT__soc_sram__DOT__sram__DOT__genblk1__BRA__17__KET____DOT__sram1;
    Vtop_sky130_sram_2kbyte_1rw1r_32x512_8* __PVT__soc_sram__DOT__sram__DOT__genblk1__BRA__18__KET____DOT__sram1;
    Vtop_sky130_sram_2kbyte_1rw1r_32x512_8* __PVT__soc_sram__DOT__sram__DOT__genblk1__BRA__19__KET____DOT__sram1;
    Vtop_sky130_sram_2kbyte_1rw1r_32x512_8* __PVT__soc_sram__DOT__sram__DOT__genblk1__BRA__20__KET____DOT__sram1;
    Vtop_sky130_sram_2kbyte_1rw1r_32x512_8* __PVT__soc_sram__DOT__sram__DOT__genblk1__BRA__21__KET____DOT__sram1;
    Vtop_sky130_sram_2kbyte_1rw1r_32x512_8* __PVT__soc_sram__DOT__sram__DOT__genblk1__BRA__22__KET____DOT__sram1;
    Vtop_sky130_sram_2kbyte_1rw1r_32x512_8* __PVT__soc_sram__DOT__sram__DOT__genblk1__BRA__23__KET____DOT__sram1;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk_i,0,0);
        VL_IN8(rst_ni,0,0);
        VL_IN8(boot_sel_soft_i,0,0);
        VL_IN8(boot_sel_src_i,0,0);
        VL_IN8(sram_mux_sel_i,0,0);
        VL_IN8(caravel_wb_rst_i,0,0);
        VL_IN8(caravel_wbs_stb_i,0,0);
        VL_IN8(caravel_wbs_cyc_i,0,0);
        VL_IN8(caravel_wbs_we_i,0,0);
        VL_IN8(caravel_wbs_sel_i,3,0);
        VL_OUT8(caravel_wbs_ack_o,0,0);
        VL_OUT8(caravel_interrupt_o,2,0);
        CData/*0:0*/ soc_sram__DOT__clk_i;
        CData/*0:0*/ soc_sram__DOT__rst_ni;
        CData/*0:0*/ soc_sram__DOT__boot_sel_soft_i;
        CData/*0:0*/ soc_sram__DOT__boot_sel_src_i;
        CData/*0:0*/ soc_sram__DOT__sram_mux_sel_i;
        CData/*0:0*/ soc_sram__DOT__caravel_wb_rst_i;
        CData/*0:0*/ soc_sram__DOT__caravel_wbs_stb_i;
        CData/*0:0*/ soc_sram__DOT__caravel_wbs_cyc_i;
        CData/*0:0*/ soc_sram__DOT__caravel_wbs_we_i;
        CData/*3:0*/ soc_sram__DOT__caravel_wbs_sel_i;
        CData/*0:0*/ soc_sram__DOT__caravel_wbs_ack_o;
        CData/*2:0*/ soc_sram__DOT__caravel_interrupt_o;
        CData/*0:0*/ soc_sram__DOT__dmem_req;
        CData/*0:0*/ soc_sram__DOT__dmem_gnt;
        CData/*0:0*/ soc_sram__DOT__dmem_we;
        CData/*0:0*/ soc_sram__DOT__dmem_rvalid;
        CData/*3:0*/ soc_sram__DOT__dmem_be;
        CData/*0:0*/ soc_sram__DOT__imem_req;
        CData/*0:0*/ soc_sram__DOT__imem_gnt;
        CData/*0:0*/ soc_sram__DOT__imem_we;
        CData/*0:0*/ soc_sram__DOT__imem_rvalid;
        CData/*3:0*/ soc_sram__DOT__imem_be;
        CData/*0:0*/ soc_sram__DOT__sram_d_req;
        CData/*0:0*/ soc_sram__DOT__sram_d_gnt;
        CData/*0:0*/ soc_sram__DOT__sram_d_we;
        CData/*0:0*/ soc_sram__DOT__sram_d_rvalid;
        CData/*3:0*/ soc_sram__DOT__sram_d_be;
        CData/*0:0*/ soc_sram__DOT__sram_i_req;
        CData/*0:0*/ soc_sram__DOT__sram_i_gnt;
        CData/*0:0*/ soc_sram__DOT__sram_i_we;
        CData/*0:0*/ soc_sram__DOT__sram_i_rvalid;
        CData/*3:0*/ soc_sram__DOT__sram_i_be;
        CData/*0:0*/ soc_sram__DOT__peripheral_req;
        CData/*0:0*/ soc_sram__DOT__peripheral_gnt;
        CData/*0:0*/ soc_sram__DOT__peripheral_we;
        CData/*0:0*/ soc_sram__DOT__peripheral_rvalid;
        CData/*3:0*/ soc_sram__DOT__peripheral_be;
        CData/*0:0*/ soc_sram__DOT__flash_req;
        CData/*0:0*/ soc_sram__DOT__flash_gnt;
        CData/*0:0*/ soc_sram__DOT__flash_we;
        CData/*0:0*/ soc_sram__DOT__flash_rvalid;
        CData/*3:0*/ soc_sram__DOT__flash_be;
        CData/*0:0*/ soc_sram__DOT__caravel_req;
        CData/*0:0*/ soc_sram__DOT__caravel_gnt;
        CData/*0:0*/ soc_sram__DOT__caravel_we;
        CData/*0:0*/ soc_sram__DOT__caravel_rvalid;
        CData/*3:0*/ soc_sram__DOT__caravel_be;
        CData/*0:0*/ soc_sram__DOT__sram_d_muxed_req;
        CData/*0:0*/ soc_sram__DOT__sram_d_muxed_gnt;
        CData/*0:0*/ soc_sram__DOT__sram_d_muxed_we;
        CData/*0:0*/ soc_sram__DOT__sram_d_muxed_rvalid;
        CData/*3:0*/ soc_sram__DOT__sram_d_muxed_be;
    };
    struct {
        CData/*4:0*/ soc_sram__DOT__rf_port1_reg;
        CData/*4:0*/ soc_sram__DOT__rf_port2_reg;
        CData/*4:0*/ soc_sram__DOT__rf_wr_reg;
        CData/*0:0*/ soc_sram__DOT__rf_wr_en;
        CData/*0:0*/ soc_sram__DOT__timer_intr;
        CData/*0:0*/ soc_sram__DOT__m_ext_intr;
        CData/*0:0*/ soc_sram__DOT__p_int_read;
        CData/*0:0*/ soc_sram__DOT__csr_busy;
        CData/*0:0*/ soc_sram__DOT__dmem_rvalid_1;
        CData/*0:0*/ soc_sram__DOT__is_sram_wrap;
        CData/*0:0*/ soc_sram__DOT__is_sram_wrap_prev;
        CData/*7:0*/ soc_sram__DOT__unused;
        CData/*0:0*/ soc_sram__DOT____Vcellinp__sram__sram_d_req_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__clk_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__rst_ni;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__timer_intr_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__m_ext_intr_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__p_int_read_o;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__csr_busy_o;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__boot_sel_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__imem_req_o;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__imem_gnt_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__imem_we_o;
        CData/*3:0*/ soc_sram__DOT__i_core__DOT__imem_be_o;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__imem_rvalid_i;
        CData/*4:0*/ soc_sram__DOT__i_core__DOT__rf_port1_reg_o;
        CData/*4:0*/ soc_sram__DOT__i_core__DOT__rf_port2_reg_o;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__rf_wr_en_o;
        CData/*4:0*/ soc_sram__DOT__i_core__DOT__rf_wr_reg_o;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__dmem_req_o;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__dmem_gnt_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__dmem_we_o;
        CData/*3:0*/ soc_sram__DOT__i_core__DOT__dmem_be_o;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__dmem_rvalid_i;
        CData/*1:0*/ soc_sram__DOT__i_core__DOT__fetch_ctrl;
        CData/*1:0*/ soc_sram__DOT__i_core__DOT__decode_ctrl;
        CData/*1:0*/ soc_sram__DOT__i_core__DOT__exec_ctrl;
        CData/*1:0*/ soc_sram__DOT__i_core__DOT__mem_ctrl;
        CData/*1:0*/ soc_sram__DOT__i_core__DOT__wb_ctrl;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__fetch_valid;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__decode_valid;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__exec_valid;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__mem_valid;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__load_use_stall;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__csr_hold;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__imem_stall;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__dmem_stall;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__branch_taken;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__pc_target_sel;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__pc_intr_sel;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__dmem_rd;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__dmem_wr;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__csr_flush;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_fetch_stage__DOT__clk_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_fetch_stage__DOT__rst_ni;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_fetch_stage__DOT__boot_sel_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_fetch_stage__DOT__target_sel_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_fetch_stage__DOT__intr_sel_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_fetch_stage__DOT__branch_desync_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_fetch_stage__DOT__branch_taken_o;
        CData/*1:0*/ soc_sram__DOT__i_core__DOT__i_fetch_stage__DOT__stage_ctrl_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_fetch_stage__DOT__valid_o;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_fetch_stage__DOT__branch_ctrl_saved;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_fetch_stage__DOT__target_sel_saved;
    };
    struct {
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_fetch_stage__DOT__target_sel;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_fetch_stage__DOT____Vcellinp__i_prog_cntr__stall_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_fetch_stage__DOT__i_prog_cntr__DOT__clk_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_fetch_stage__DOT__i_prog_cntr__DOT__rst_ni;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_fetch_stage__DOT__i_prog_cntr__DOT__boot_sel_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_fetch_stage__DOT__i_prog_cntr__DOT__stall_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__clk_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__rst_ni;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__valid_i;
        CData/*1:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__stage_ctrl_i;
        CData/*4:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__rf_port1_reg_o;
        CData/*4:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__rf_port2_reg_o;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__valid_o;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__pc_src;
        CData/*2:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__branch_op;
        CData/*3:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__alu_op;
        CData/*1:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__alu_a_src;
        CData/*1:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__alu_b_src;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__rf_wr_en;
        CData/*1:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__rf_wr_src;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__mem_write;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__mem_read;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__mem_sign;
        CData/*1:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__mem_width;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__rs1_used;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__rs2_used;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__rd_used;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__csr_wr;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__csr_mret;
        CData/*4:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__rd_addr;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__i_decoder__DOT__pc_src_o;
        CData/*2:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__i_decoder__DOT__branch_op_o;
        CData/*3:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__i_decoder__DOT__alu_op_o;
        CData/*1:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__i_decoder__DOT__alu_a_src_o;
        CData/*1:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__i_decoder__DOT__alu_b_src_o;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__i_decoder__DOT__rs1_valid_o;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__i_decoder__DOT__rs2_valid_o;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__i_decoder__DOT__rd_valid_o;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__i_decoder__DOT__rf_wr_en_o;
        CData/*1:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__i_decoder__DOT__rf_wr_src_o;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__i_decoder__DOT__mem_write_o;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__i_decoder__DOT__mem_read_o;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__i_decoder__DOT__mem_sign_o;
        CData/*1:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__i_decoder__DOT__mem_width_o;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__i_decoder__DOT__csr_wr_o;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__i_decoder__DOT__csr_mret_o;
        CData/*6:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__i_decoder__DOT__opcode;
        CData/*2:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__i_decoder__DOT__func3;
        CData/*6:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__i_decoder__DOT__func7;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__i_decoder__DOT__csr_en;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__i_decoder__DOT__inst_unused;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__i_decoder__DOT__func7_unused;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__i_immed_gen__DOT__inst_unused;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__clk_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__rst_ni;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__valid_i;
        CData/*1:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__stage_ctrl_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__target_sel_o;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__valid_o;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__mem_read_ao;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__mem_write_ao;
        CData/*3:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__mem_strb_ao;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__branch_taken;
        CData/*3:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__mem_strb;
    };
    struct {
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__mem_read;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__mem_write;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__mem_illegal;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__valid;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT_____05Funused;
        CData/*3:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__i_alu__DOT__op_i;
        CData/*2:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__i_branch_gen__DOT__op_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__i_branch_gen__DOT__taken_o;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__i_branch_gen__DOT__eq;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__i_branch_gen__DOT__lt;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__i_branch_gen__DOT__ltu;
        CData/*1:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__i_mem_prep__DOT__mem_width_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__i_mem_prep__DOT__mem_read_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__i_mem_prep__DOT__mem_write_i;
        CData/*3:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__i_mem_prep__DOT__mem_strobe_ao;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__i_mem_prep__DOT__mem_illegal_ao;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__i_mem_prep__DOT__illegal_addr;
        CData/*1:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__i_mem_prep__DOT__pre_width;
        CData/*1:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__i_mem_prep__DOT__req_byte_idx;
        CData/*3:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__i_mem_prep__DOT__req_strobe;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_mem_slice_stage__DOT__clk_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_mem_slice_stage__DOT__rst_ni;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_mem_slice_stage__DOT__valid_i;
        CData/*1:0*/ soc_sram__DOT__i_core__DOT__i_mem_slice_stage__DOT__stage_ctrl_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_mem_slice_stage__DOT__valid_o;
        CData/*1:0*/ soc_sram__DOT__i_core__DOT__i_mem_slice_stage__DOT__byte_offset;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_mem_slice_stage__DOT__sign;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_mem_slice_stage__DOT__sign_ext;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_wb_stage__DOT__valid_i;
        CData/*1:0*/ soc_sram__DOT__i_core__DOT__i_wb_stage__DOT__stage_ctrl_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_wb_stage__DOT__rf_wr_en_oa;
        CData/*4:0*/ soc_sram__DOT__i_core__DOT__i_wb_stage__DOT__rf_wr_reg_oa;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_wb_stage__DOT___unused;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_csr__DOT__clk_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_csr__DOT__rst_ni;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_csr__DOT__csr_wr_i;
        CData/*1:0*/ soc_sram__DOT__i_core__DOT__i_csr__DOT__mode_sel_i;
        CData/*4:0*/ soc_sram__DOT__i_core__DOT__i_csr__DOT__immed_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_csr__DOT__immed_sel_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_csr__DOT__timer_intr_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_csr__DOT__m_ext_intr_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_csr__DOT__stall_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_csr__DOT__mret_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_csr__DOT__pcSource;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_csr__DOT__csr_hold_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_csr__DOT__csr_flush_o;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_csr__DOT__pc_intr_sel;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_csr__DOT__p_int_read_o;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_csr__DOT__csr_busy_o;
        CData/*4:0*/ soc_sram__DOT__i_core__DOT__i_csr__DOT__int_state;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_fwd_unit__DOT__load_use_stall_ao;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_fwd_unit__DOT__rs1_lus;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_fwd_unit__DOT__rs2_lus;
        CData/*4:0*/ soc_sram__DOT__i_core__DOT__i_fwd_unit__DOT__rs1_fwd_unit__DOT__rs_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_fwd_unit__DOT__rs1_fwd_unit__DOT__rs_used_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_fwd_unit__DOT__rs1_fwd_unit__DOT__load_use_hazard_ao;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_fwd_unit__DOT__rs1_fwd_unit__DOT__mem_conflict;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_fwd_unit__DOT__rs1_fwd_unit__DOT__ex_conflict;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_fwd_unit__DOT__rs1_fwd_unit__DOT__mem_raw;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_fwd_unit__DOT__rs1_fwd_unit__DOT__ex_raw;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_fwd_unit__DOT__rs1_fwd_unit__DOT___unused;
        CData/*4:0*/ soc_sram__DOT__i_core__DOT__i_fwd_unit__DOT__rs2_fwd_unit__DOT__rs_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_fwd_unit__DOT__rs2_fwd_unit__DOT__rs_used_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_fwd_unit__DOT__rs2_fwd_unit__DOT__load_use_hazard_ao;
    };
    struct {
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_fwd_unit__DOT__rs2_fwd_unit__DOT__mem_conflict;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_fwd_unit__DOT__rs2_fwd_unit__DOT__ex_conflict;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_fwd_unit__DOT__rs2_fwd_unit__DOT__mem_raw;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_fwd_unit__DOT__rs2_fwd_unit__DOT__ex_raw;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_fwd_unit__DOT__rs2_fwd_unit__DOT___unused;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_imem_obi_driver__DOT__clk_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_imem_obi_driver__DOT__rst_ni;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_imem_obi_driver__DOT__rd_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_imem_obi_driver__DOT__wr_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_imem_obi_driver__DOT__gnt_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_imem_obi_driver__DOT__rvalid_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_imem_obi_driver__DOT__stall_o;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_imem_obi_driver__DOT__req_o;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_imem_obi_driver__DOT__NS;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_imem_obi_driver__DOT__PS;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_imem_obi_driver__DOT__gnt_buf;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_imem_obi_driver__DOT__rvalid_buf;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_imem_obi_driver__DOT__outstanding_read;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_dmem_obi_driver__DOT__clk_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_dmem_obi_driver__DOT__rst_ni;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_dmem_obi_driver__DOT__rd_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_dmem_obi_driver__DOT__wr_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_dmem_obi_driver__DOT__gnt_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_dmem_obi_driver__DOT__rvalid_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_dmem_obi_driver__DOT__stall_o;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_dmem_obi_driver__DOT__req_o;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_dmem_obi_driver__DOT__NS;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_dmem_obi_driver__DOT__PS;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_dmem_obi_driver__DOT__gnt_buf;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_dmem_obi_driver__DOT__rvalid_buf;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_dmem_obi_driver__DOT__outstanding_read;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_hazard_unit__DOT__clk_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_hazard_unit__DOT__rst_ni;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_hazard_unit__DOT__imem_stall_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_hazard_unit__DOT__dmem_stall_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_hazard_unit__DOT__branch_taken_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_hazard_unit__DOT__csr_flush_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_hazard_unit__DOT__csr_mret_i;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_hazard_unit__DOT__load_use_stall_i;
        CData/*1:0*/ soc_sram__DOT__i_core__DOT__i_hazard_unit__DOT__fetch_ctrl_ao;
        CData/*1:0*/ soc_sram__DOT__i_core__DOT__i_hazard_unit__DOT__decode_ctrl_ao;
        CData/*1:0*/ soc_sram__DOT__i_core__DOT__i_hazard_unit__DOT__execute_ctrl_ao;
        CData/*1:0*/ soc_sram__DOT__i_core__DOT__i_hazard_unit__DOT__memory_ctrl_ao;
        CData/*1:0*/ soc_sram__DOT__i_core__DOT__i_hazard_unit__DOT__writeback_ctrl_ao;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_hazard_unit__DOT__csr_hold_o;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_hazard_unit__DOT__flush_in_progess;
        CData/*0:0*/ soc_sram__DOT__i_core__DOT__i_hazard_unit__DOT__branch;
        CData/*2:0*/ soc_sram__DOT__i_core__DOT__i_hazard_unit__DOT__PS;
        CData/*2:0*/ soc_sram__DOT__i_core__DOT__i_hazard_unit__DOT__NS;
        CData/*0:0*/ soc_sram__DOT__i_reg_file__DOT__clk_i;
        CData/*4:0*/ soc_sram__DOT__i_reg_file__DOT__read1_i;
        CData/*4:0*/ soc_sram__DOT__i_reg_file__DOT__read2_i;
        CData/*4:0*/ soc_sram__DOT__i_reg_file__DOT__wr_reg_i;
        CData/*0:0*/ soc_sram__DOT__i_reg_file__DOT__wr_en_i;
        CData/*0:0*/ soc_sram__DOT__sram__DOT__clk_i;
        CData/*0:0*/ soc_sram__DOT__sram__DOT__rst_ni;
        CData/*0:0*/ soc_sram__DOT__sram__DOT__sram_d_req_i;
        CData/*0:0*/ soc_sram__DOT__sram__DOT__sram_d_gnt_o;
        CData/*0:0*/ soc_sram__DOT__sram__DOT__sram_d_we_i;
        CData/*3:0*/ soc_sram__DOT__sram__DOT__sram_d_be_i;
        CData/*0:0*/ soc_sram__DOT__sram__DOT__sram_d_rvalid_o;
        CData/*0:0*/ soc_sram__DOT__sram__DOT__sram_i_req_i;
        CData/*0:0*/ soc_sram__DOT__sram__DOT__sram_i_gnt_o;
        CData/*0:0*/ soc_sram__DOT__sram__DOT__sram_i_we_i;
    };
    struct {
        CData/*3:0*/ soc_sram__DOT__sram__DOT__sram_i_be_i;
        CData/*0:0*/ soc_sram__DOT__sram__DOT__sram_i_rvalid_o;
        CData/*0:0*/ soc_sram__DOT__sram__DOT__illegal_memory_o;
        CData/*4:0*/ soc_sram__DOT__sram__DOT__sram_d_cs_addr;
        CData/*4:0*/ soc_sram__DOT__sram__DOT__sram_i_cs_addr;
        CData/*4:0*/ soc_sram__DOT__sram__DOT__unnamedblk1__DOT__i;
        CData/*0:0*/ soc_sram__DOT__i_memory__DOT__clk_i;
        CData/*0:0*/ soc_sram__DOT__i_memory__DOT__pA_en_i;
        CData/*3:0*/ soc_sram__DOT__i_memory__DOT__pA_strobe_i;
        CData/*0:0*/ soc_sram__DOT__i_memory__DOT__pB_en_i;
        CData/*3:0*/ soc_sram__DOT__i_memory__DOT__pB_strobe_i;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__0__KET____DOT__sram1__clk0__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__0__KET____DOT__sram1__clk1__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__1__KET____DOT__sram1__clk0__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__1__KET____DOT__sram1__clk1__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__2__KET____DOT__sram1__clk0__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__2__KET____DOT__sram1__clk1__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__3__KET____DOT__sram1__clk0__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__3__KET____DOT__sram1__clk1__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__4__KET____DOT__sram1__clk0__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__4__KET____DOT__sram1__clk1__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__5__KET____DOT__sram1__clk0__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__5__KET____DOT__sram1__clk1__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__6__KET____DOT__sram1__clk0__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__6__KET____DOT__sram1__clk1__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__7__KET____DOT__sram1__clk0__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__7__KET____DOT__sram1__clk1__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__8__KET____DOT__sram1__clk0__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__8__KET____DOT__sram1__clk1__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__9__KET____DOT__sram1__clk0__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__9__KET____DOT__sram1__clk1__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__10__KET____DOT__sram1__clk0__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__10__KET____DOT__sram1__clk1__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__11__KET____DOT__sram1__clk0__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__11__KET____DOT__sram1__clk1__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__12__KET____DOT__sram1__clk0__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__12__KET____DOT__sram1__clk1__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__13__KET____DOT__sram1__clk0__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__13__KET____DOT__sram1__clk1__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__14__KET____DOT__sram1__clk0__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__14__KET____DOT__sram1__clk1__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__15__KET____DOT__sram1__clk0__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__15__KET____DOT__sram1__clk1__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__16__KET____DOT__sram1__clk0__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__16__KET____DOT__sram1__clk1__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__17__KET____DOT__sram1__clk0__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__17__KET____DOT__sram1__clk1__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__18__KET____DOT__sram1__clk0__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__18__KET____DOT__sram1__clk1__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__19__KET____DOT__sram1__clk0__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__19__KET____DOT__sram1__clk1__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__20__KET____DOT__sram1__clk0__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__20__KET____DOT__sram1__clk1__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__21__KET____DOT__sram1__clk0__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__21__KET____DOT__sram1__clk1__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__22__KET____DOT__sram1__clk0__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__22__KET____DOT__sram1__clk1__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__23__KET____DOT__sram1__clk0__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_sram__DOT__sram__DOT__genblk1__BRA__23__KET____DOT__sram1__clk1__0;
        CData/*0:0*/ __VactContinue;
        SData/*11:0*/ soc_sram__DOT__i_core__DOT__i_csr__DOT__addr_i;
        SData/*15:0*/ soc_sram__DOT__i_memory__DOT__pA_addr_i;
    };
    struct {
        SData/*15:0*/ soc_sram__DOT__i_memory__DOT__pB_addr_i;
        VL_IN(caravel_wbs_dat_i,31,0);
        VL_IN(caravel_wbs_adr_i,31,0);
        VL_OUT(caravel_wbs_dat_o,31,0);
        VL_INW(la_data_i,127,0,4);
        VL_OUTW(la_data_o,127,0,4);
        VL_INW(la_oe_no,127,0,4);
        IData/*31:0*/ soc_sram__DOT__caravel_wbs_dat_i;
        IData/*31:0*/ soc_sram__DOT__caravel_wbs_adr_i;
        IData/*31:0*/ soc_sram__DOT__caravel_wbs_dat_o;
        VlWide<4>/*127:0*/ soc_sram__DOT__la_data_i;
        VlWide<4>/*127:0*/ soc_sram__DOT__la_data_o;
        VlWide<4>/*127:0*/ soc_sram__DOT__la_oe_no;
        IData/*31:0*/ soc_sram__DOT__dmem_addr;
        IData/*31:0*/ soc_sram__DOT__dmem_wdata;
        IData/*31:0*/ soc_sram__DOT__dmem_rdata;
        IData/*31:0*/ soc_sram__DOT__imem_addr;
        IData/*31:0*/ soc_sram__DOT__imem_wdata;
        IData/*31:0*/ soc_sram__DOT__imem_rdata;
        IData/*31:0*/ soc_sram__DOT__sram_d_addr;
        IData/*31:0*/ soc_sram__DOT__sram_d_wdata;
        IData/*31:0*/ soc_sram__DOT__sram_d_rdata;
        IData/*31:0*/ soc_sram__DOT__sram_i_addr;
        IData/*31:0*/ soc_sram__DOT__sram_i_wdata;
        IData/*31:0*/ soc_sram__DOT__sram_i_rdata;
        IData/*31:0*/ soc_sram__DOT__peripheral_addr;
        IData/*31:0*/ soc_sram__DOT__peripheral_wdata;
        IData/*31:0*/ soc_sram__DOT__peripheral_rdata;
        IData/*31:0*/ soc_sram__DOT__flash_addr;
        IData/*31:0*/ soc_sram__DOT__flash_wdata;
        IData/*31:0*/ soc_sram__DOT__flash_rdata;
        IData/*31:0*/ soc_sram__DOT__caravel_addr;
        IData/*31:0*/ soc_sram__DOT__caravel_wdata;
        IData/*31:0*/ soc_sram__DOT__caravel_rdata;
        IData/*31:0*/ soc_sram__DOT__sram_d_muxed_addr;
        IData/*31:0*/ soc_sram__DOT__sram_d_muxed_wdata;
        IData/*31:0*/ soc_sram__DOT__sram_d_muxed_rdata;
        IData/*31:0*/ soc_sram__DOT__rf_rs1;
        IData/*31:0*/ soc_sram__DOT__rf_rs2;
        IData/*31:0*/ soc_sram__DOT__rf_wr_data;
        IData/*30:0*/ soc_sram__DOT__mcause;
        IData/*31:0*/ soc_sram__DOT__dmem_rdata_1;
        IData/*31:0*/ soc_sram__DOT__dmem_rdata_2;
        VlWide<4>/*127:0*/ soc_sram__DOT__unused2;
        VlWide<4>/*127:0*/ soc_sram__DOT___unused;
        IData/*30:0*/ soc_sram__DOT__i_core__DOT__mcause_i;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__imem_addr_o;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__imem_wdata_o;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__imem_rdata_i;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__rf_wr_data_o;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__rf_rs1_i;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__rf_rs2_i;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__dmem_addr_o;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__dmem_wdata_o;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__dmem_rdata_i;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__pc_target_addr;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__pc_intr_addr;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__pre_intr_pc;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__csr_out;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_fetch_stage__DOT__target_addr_i;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_fetch_stage__DOT__intr_addr_i;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_fetch_stage__DOT__mem_addr_o;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_fetch_stage__DOT__pre_intr_pc_o;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_fetch_stage__DOT__pc_next;
    };
    struct {
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_fetch_stage__DOT__pc_out;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_fetch_stage__DOT__pc_plus_4;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_fetch_stage__DOT__target_saved;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_fetch_stage__DOT__target_addr;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_fetch_stage__DOT__i_prog_cntr__DOT__next_pc_i;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_fetch_stage__DOT__i_prog_cntr__DOT__pc_o;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_fetch_stage__DOT__i_prog_cntr__DOT__reset_addr;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_fetch_stage__DOT__i_prog_cntr__DOT__last_pc;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_fetch_stage__DOT__i_prog_cntr__DOT__pc_raw;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__inst_i;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__rf_rs1_i;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__rf_rs2_i;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__i_immed;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__s_immed;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__b_immed;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__u_immed;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__j_immed;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__i_decoder__DOT__inst_i;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__i_immed_gen__DOT__inst_i;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__i_immed_gen__DOT__i_immed_o;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__i_immed_gen__DOT__s_immed_o;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__i_immed_gen__DOT__b_immed_o;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__i_immed_gen__DOT__u_immed_o;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__i_immed_gen__DOT__j_immed_o;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__csr_read_i;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__target_addr_o;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__mem_addr_ao;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__mem_data_ao;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__alu_a_in;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__alu_b_in;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__alu_out;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__mem_addr;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__mem_wdata;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__last_dmem_addr;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__i_alu__DOT__a_i;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__i_alu__DOT__b_i;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__i_alu__DOT__out_o;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__i_branch_gen__DOT__rs1_data_i;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__i_branch_gen__DOT__rs2_data_i;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__i_mem_prep__DOT__mem_data_i;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__i_mem_prep__DOT__mem_addr_i;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__i_mem_prep__DOT__mem_word_addr_ao;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__i_mem_prep__DOT__mem_write_data_ao;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__i_mem_prep__DOT__pre_write_data;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__i_mem_prep__DOT__req_write_data;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_mem_slice_stage__DOT__dmem_rdata_i;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_mem_slice_stage__DOT__pre_data;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_wb_stage__DOT__rf_wr_data_oa;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_wb_stage__DOT__rf_wr_data;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_csr__DOT__rs1;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_csr__DOT__next_pc;
        IData/*30:0*/ soc_sram__DOT__i_core__DOT__i_csr__DOT__mcause_i;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_csr__DOT__csr_data_o;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_csr__DOT__pc_intr_addr;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_csr__DOT__mstatus;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_csr__DOT__mie;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_csr__DOT__mtvec;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_csr__DOT__mepc;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_csr__DOT__mcause;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_csr__DOT__write_data;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_fwd_unit__DOT__rs1_updated;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_fwd_unit__DOT__rs2_updated;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_fwd_unit__DOT__rs1_fwd_unit__DOT__rs_data_i;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_fwd_unit__DOT__rs1_fwd_unit__DOT__rs_data_ao;
    };
    struct {
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_fwd_unit__DOT__rs1_fwd_unit__DOT__data_updated_mem;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_fwd_unit__DOT__rs2_fwd_unit__DOT__rs_data_i;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_fwd_unit__DOT__rs2_fwd_unit__DOT__rs_data_ao;
        IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_fwd_unit__DOT__rs2_fwd_unit__DOT__data_updated_mem;
        IData/*31:0*/ soc_sram__DOT__i_reg_file__DOT__wr_data_i;
        IData/*31:0*/ soc_sram__DOT__i_reg_file__DOT__data1_ao;
        IData/*31:0*/ soc_sram__DOT__i_reg_file__DOT__data2_ao;
        IData/*31:0*/ soc_sram__DOT__sram__DOT__sram_d_addr_i;
        IData/*31:0*/ soc_sram__DOT__sram__DOT__sram_d_wdata_i;
        IData/*31:0*/ soc_sram__DOT__sram__DOT__sram_d_rdata_o;
        IData/*31:0*/ soc_sram__DOT__sram__DOT__sram_i_addr_i;
        IData/*31:0*/ soc_sram__DOT__sram__DOT__sram_i_wdata_i;
        IData/*31:0*/ soc_sram__DOT__sram__DOT__sram_i_rdata_o;
        IData/*23:0*/ soc_sram__DOT__sram__DOT__cs_data;
        IData/*23:0*/ soc_sram__DOT__sram__DOT__cs_inst;
        IData/*23:0*/ soc_sram__DOT__sram__DOT__cs_data_prev;
        IData/*23:0*/ soc_sram__DOT__sram__DOT__cs_inst_prev;
        IData/*31:0*/ soc_sram__DOT__i_memory__DOT__pA_data_i;
        IData/*31:0*/ soc_sram__DOT__i_memory__DOT__pB_data_i;
        IData/*31:0*/ soc_sram__DOT__i_memory__DOT__pA_data_o;
        IData/*31:0*/ soc_sram__DOT__i_memory__DOT__pB_data_o;
        IData/*31:0*/ soc_sram__DOT__i_memory__DOT__i;
        IData/*31:0*/ __VstlIterCount;
        IData/*31:0*/ __VicoIterCount;
        IData/*31:0*/ __VactIterCount;
        VL_IN64(gpio_i,37,0);
        VL_OUT64(gpio_o,37,0);
        VL_OUT64(gpio_oeb_no,37,0);
        QData/*37:0*/ soc_sram__DOT__gpio_i;
        QData/*37:0*/ soc_sram__DOT__gpio_o;
        QData/*37:0*/ soc_sram__DOT__gpio_oeb_no;
        QData/*63:0*/ soc_sram__DOT__i_core__DOT__fetch_state;
        VlWide<9>/*265:0*/ soc_sram__DOT__i_core__DOT__decode_state;
        VlWide<4>/*102:0*/ soc_sram__DOT__i_core__DOT__exec_state;
        VlWide<5>/*134:0*/ soc_sram__DOT__i_core__DOT__mem_state;
        VlWide<3>/*81:0*/ soc_sram__DOT__i_core__DOT__decode_reg_meta;
        VlWide<3>/*81:0*/ soc_sram__DOT__i_core__DOT__decode_reg_meta_updated;
        VlWide<3>/*81:0*/ soc_sram__DOT__i_core__DOT__exec_reg_meta;
        VlWide<3>/*81:0*/ soc_sram__DOT__i_core__DOT__mem_reg_meta;
        QData/*39:0*/ soc_sram__DOT__i_core__DOT__mem_fwd_data;
        QData/*39:0*/ soc_sram__DOT__i_core__DOT__wb_fwd_data;
        QData/*63:0*/ soc_sram__DOT__i_core__DOT__i_fetch_stage__DOT__fetch_state_o;
        QData/*63:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__fetch_state_i;
        VlWide<9>/*265:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__decode_state_o;
        VlWide<3>/*81:0*/ soc_sram__DOT__i_core__DOT__i_decode_stage__DOT__reg_meta_o;
        VlWide<9>/*265:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__decode_state_i;
        VlWide<3>/*81:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__reg_meta_i;
        VlWide<4>/*102:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__exec_state_o;
        VlWide<3>/*81:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__reg_meta_o;
        VlWide<4>/*102:0*/ soc_sram__DOT__i_core__DOT__i_mem_slice_stage__DOT__exec_state_i;
        VlWide<3>/*81:0*/ soc_sram__DOT__i_core__DOT__i_mem_slice_stage__DOT__reg_meta_i;
        VlWide<5>/*134:0*/ soc_sram__DOT__i_core__DOT__i_mem_slice_stage__DOT__mem_state_o;
        VlWide<3>/*81:0*/ soc_sram__DOT__i_core__DOT__i_mem_slice_stage__DOT__reg_meta_o;
        QData/*39:0*/ soc_sram__DOT__i_core__DOT__i_mem_slice_stage__DOT__data_fwd_oa;
        VlWide<5>/*134:0*/ soc_sram__DOT__i_core__DOT__i_wb_stage__DOT__mem_state_i;
        VlWide<3>/*81:0*/ soc_sram__DOT__i_core__DOT__i_wb_stage__DOT__reg_meta_i;
        QData/*39:0*/ soc_sram__DOT__i_core__DOT__i_wb_stage__DOT__data_fwd_oa;
        QData/*39:0*/ soc_sram__DOT__i_core__DOT__i_fwd_unit__DOT__ex_stage_i;
        QData/*39:0*/ soc_sram__DOT__i_core__DOT__i_fwd_unit__DOT__mem_stage_i;
        VlWide<3>/*81:0*/ soc_sram__DOT__i_core__DOT__i_fwd_unit__DOT__dest_meta_i;
        VlWide<3>/*81:0*/ soc_sram__DOT__i_core__DOT__i_fwd_unit__DOT__dest_meta_o;
        QData/*39:0*/ soc_sram__DOT__i_core__DOT__i_fwd_unit__DOT__rs1_fwd_unit__DOT__ex_stage_i;
        QData/*39:0*/ soc_sram__DOT__i_core__DOT__i_fwd_unit__DOT__rs1_fwd_unit__DOT__mem_stage_i;
        QData/*39:0*/ soc_sram__DOT__i_core__DOT__i_fwd_unit__DOT__rs2_fwd_unit__DOT__ex_stage_i;
    };
    struct {
        QData/*39:0*/ soc_sram__DOT__i_core__DOT__i_fwd_unit__DOT__rs2_fwd_unit__DOT__mem_stage_i;
        VlUnpacked<CData/*7:0*/, 4> soc_sram__DOT__i_core__DOT__i_mem_slice_stage__DOT__bytes;
        VlUnpacked<SData/*15:0*/, 2> soc_sram__DOT__i_core__DOT__i_mem_slice_stage__DOT__halfs;
        VlUnpacked<IData/*31:0*/, 32> soc_sram__DOT__i_reg_file__DOT__RF;
        VlUnpacked<IData/*31:0*/, 24> soc_sram__DOT__sram__DOT__sram_d_read_vec;
        VlUnpacked<IData/*31:0*/, 24> soc_sram__DOT__sram__DOT__sram_i_read_vec;
        VlUnpacked<IData/*31:0*/, 65536> soc_sram__DOT__i_memory__DOT__ram_block;
    };
    VlDelayScheduler __VdlySched;
    VlTriggerScheduler __VtrigSched_h67d39080__0;
    VlTriggerScheduler __VtrigSched_he9ec4173__0;
    VlTriggerScheduler __VtrigSched_h253e2db3__0;
    VlTriggerScheduler __VtrigSched_h97281d72__0;
    VlTriggerScheduler __VtrigSched_h3463749e__0;
    VlTriggerScheduler __VtrigSched_h5052b3d5__0;
    VlTriggerScheduler __VtrigSched_hddcad66b__0;
    VlTriggerScheduler __VtrigSched_h43c15422__0;
    VlTriggerScheduler __VtrigSched_hd41dc089__0;
    VlTriggerScheduler __VtrigSched_h333aa9a2__0;
    VlTriggerScheduler __VtrigSched_h14eb4f87__0;
    VlTriggerScheduler __VtrigSched_hca45ca3d__0;
    VlTriggerScheduler __VtrigSched_h961577d8__0;
    VlTriggerScheduler __VtrigSched_h2e11fceb__0;
    VlTriggerScheduler __VtrigSched_h311a0fdd__0;
    VlTriggerScheduler __VtrigSched_h40bbc52e__0;
    VlTriggerScheduler __VtrigSched_h75c42fb9__0;
    VlTriggerScheduler __VtrigSched_hd5e3f254__0;
    VlTriggerScheduler __VtrigSched_h1afec056__0;
    VlTriggerScheduler __VtrigSched_he5c16347__0;
    VlTriggerScheduler __VtrigSched_ha3460daa__0;
    VlTriggerScheduler __VtrigSched_h02a1e423__0;
    VlTriggerScheduler __VtrigSched_h097ce1b6__0;
    VlTriggerScheduler __VtrigSched_h1d2e6b6d__0;
    VlTriggerScheduler __VtrigSched_h4b79150a__0;
    VlTriggerScheduler __VtrigSched_h518d5809__0;
    VlTriggerScheduler __VtrigSched_h5d309058__0;
    VlTriggerScheduler __VtrigSched_hc22db79f__0;
    VlTriggerScheduler __VtrigSched_he19d1911__0;
    VlTriggerScheduler __VtrigSched_hfc479460__0;
    VlTriggerScheduler __VtrigSched_hf1352a5e__0;
    VlTriggerScheduler __VtrigSched_h219ec62d__0;
    VlTriggerScheduler __VtrigSched_h4caebb08__0;
    VlTriggerScheduler __VtrigSched_h9671842a__0;
    VlTriggerScheduler __VtrigSched_h18f65c64__0;
    VlTriggerScheduler __VtrigSched_h2eb7fd9f__0;
    VlTriggerScheduler __VtrigSched_h7854963a__0;
    VlTriggerScheduler __VtrigSched_hd3c35029__0;
    VlTriggerScheduler __VtrigSched_h0627e790__0;
    VlTriggerScheduler __VtrigSched_h6eb1b43b__0;
    VlTriggerScheduler __VtrigSched_h5d812ed0__0;
    VlTriggerScheduler __VtrigSched_h1f99dd53__0;
    VlTriggerScheduler __VtrigSched_h87739dfb__0;
    VlTriggerScheduler __VtrigSched_h73c08076__0;
    VlTriggerScheduler __VtrigSched_h89387e7a__0;
    VlTriggerScheduler __VtrigSched_h9f2f7633__0;
    VlTriggerScheduler __VtrigSched_h3b2f7714__0;
    VlTriggerScheduler __VtrigSched_h0f93956f__0;
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<148> __VactTriggered;
    VlTriggerVec<148> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr IData/*31:0*/ soc_sram__DOT__ADDR_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_fetch_stage__DOT__i_prog_cntr__DOT__BOOTLOADER_ADDR = 0U;
    static constexpr IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_fetch_stage__DOT__i_prog_cntr__DOT__FAILSAFE_ADDR = 0x80000000U;
    static constexpr IData/*31:0*/ soc_sram__DOT__i_core__DOT__i_exec_stage__DOT__i_alu__DOT__Width = 0x00000020U;
    static constexpr IData/*31:0*/ soc_sram__DOT__sram__DOT__SRAM_BASE_ADDR = 0x80000000U;
    static constexpr IData/*31:0*/ soc_sram__DOT__sram__DOT__SRAM_END_ADDR = 0x8000c000U;
    static constexpr IData/*31:0*/ soc_sram__DOT__sram__DOT__SRAM_NUM_BLOCKS = 0x00000018U;
    static constexpr IData/*31:0*/ soc_sram__DOT__sram__DOT__SRAM_LOG_BLOCKS = 5U;
    static constexpr IData/*31:0*/ soc_sram__DOT__sram__DOT__SRAM_LOG_BLOCK_SIZE = 9U;
    static constexpr IData/*31:0*/ soc_sram__DOT__i_memory__DOT__NUM_COL = 4U;
    static constexpr IData/*31:0*/ soc_sram__DOT__i_memory__DOT__COL_WIDTH = 8U;
    static constexpr IData/*31:0*/ soc_sram__DOT__i_memory__DOT__ADDR_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ soc_sram__DOT__i_memory__DOT__DATA_WIDTH = 0x00000020U;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* v__name);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
    void __vlCoverInsert(std::atomic<uint32_t>* countp, bool enable, const char* filenamep, int lineno, int column,
        const char* hierp, const char* pagep, const char* commentp, const char* linescovp);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);


#endif  // guard
